### ISSUE TITLE
Missing mapbox choropleth docs in R

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.r-docs#18]
@tristanga @sacul-git figured out how to make this work... @Mahdis-z can you sync up with them and get an R version of https://plot.ly/python/mapbox-county-choropleth/ up please? Plotly.R already supports plotly.js 1.49+ today so this isn't blocked.

**Comment by tristanga** [comment]
@Mahdis-z provided 2 working examples ;) Let me know if there is anything else I can do.
