### ISSUE TITLE
p to fig

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.r-docs#19]
This kind of example:

```r
p <- plot_ly(x = ~s, y = ~s) %>%  layout(xaxis = a, yaxis = a)
p
```

should be rewritten as

```r
fig <- plot_ly(x = ~s, y = ~s) 
fig <- fig %>% layout(xaxis = a, yaxis = a)
fig
```

**Comment by nicolaskruchten** [comment]
@rpkyle @sacul-git @HammadTheOne any strong feelings here?

**Comment by sacul-git** [comment]
@nicolaskruchten is this just for readability? I personally tend to use something along the lines of the original example, creating the `fig` in one go rather than creating it and overwriting, but what are the disadvantages to having something like this in the documentation?

```
fig <- plot_ly(x = ~s, y = ~s) %>%
    layout(xaxis = a, yaxis = a)
fig
```

**Comment by HammadTheOne** [comment]
I don't feel too strongly about it, but from a user standpoint, the rewritten version might be better to follow for individuals who aren't as familiar with the `tidyverse`. In their [style guide](https://style.tidyverse.org/pipes.html) they actually recommend using shorter pipes for readability, so the rewrite is a better option from that standpoint.

**Comment by nicolaskruchten** [comment]
@sacul-git the idea is to more clearly break out the various steps for users, so they can copy-paste individual lines into their script more easily:

```r
fig <- plot_ly(x = ~s, y = ~s)                         # create fig
fig <- fig %>% layout(xaxis = a, yaxis = a)  # mutate fig
fig                                                                    # display fig
```

**Comment by nicolaskruchten** [comment]
agreed on that on the command-line you would likely just use the pipe without any assignment :)

**Comment by rpkyle** [comment]
For posterity's sake, just noting here that I made a comment along the lines of what @sacul-git said above to @nicolaskruchten, but the explanation (being able to easily copy the line and reuse) makes a lot of sense, so I have no objections to this syntax personally.
