### ISSUE TITLE
Examples charts not showing

### ISSUE THREAD

**Issue by apal0934** [plotly/plotly.r-docs#59]
Hi,

The examples charts on the R plotly site no longer display (see [line and scatter](https://plotly.com/r/line-and-scatter/) for example). 

In the console it has the error `TypeError: Plotly.plot is not a function. (In 'Plotly.plot(graphDiv, x)', 'Plotly.plot' is undefined)`

Not sure if this is most or all charts, but the few pages I clicked through all have this issue.

**Comment by nicolaskruchten** [comment]
Thank you for the heads-up! Should be fixed now :)

**Comment by donojazz** [comment]
Is this fixed?  The code runs but no map displays
