### ISSUE TITLE
CI has SSL issues

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.r-docs#6]
@jdamiba can you try to get this CI job running again please? Something changed upstream I think. I messed around with it a bit but wasn’t able to make progress... reach out to @HammadTheOne or @sacul-git if you get stuck?

**Comment by jdamiba** [comment]
@nicolaskruchten  

I have created https://github.com/plotly/plotly.r-docs/pull/7 which addresses this issue. CI passes on the branch with some small modifications to two of the examples.
