### ISSUE TITLE
plotly.express & px.parallel_categorie does not show the map and any info

### ISSUE THREAD

**Issue by Warlock0093** [plotly/plotly.r-docs#60]
I need to use plotly.express and px.parallel_categorie library but the code shows nothing, just a white screen (see attachment), where am I wrong. Or followed many online guides, installing and re-staging ploty. But nothing.  

![image](https://user-images.githubusercontent.com/85396602/120891742-79c72900-c60a-11eb-9741-68d916d6ba4e.png)
MY CODE in JUPYTERLAB

**Comment by nicolaskruchten** [comment]
Have you followed the steps in https://plotly.com/python/troubleshooting/ ?

**Comment by Warlock0093** [comment]
> https://plotly.com/python/troubleshooting/

Yes, but I still have the same problem.

**Comment by Warlock0093** [comment]
I solved, i redeemed the code on jupiter and not on jupiterlab from anaconda.
